data_path: './week_1/day_1/Salary_dataset.csv'
test_size: 0.2
random_state: 42
model:
  type: "linear_regression_scratch"
  hyperparams:
    learning_rate: 0.01
    epochs: 1000
logging:
  log_dir: "logs/"
  level: "INFO"
